### PR TITLE
Update regridding API naming convention

### LINKED ISSUE #501: [Doc]: Consider updating the listed APIs for horizontal regridding
### Describe your documentation update

After revisiting the horizontal regridding APIs we have listed in the [API Reference](https://xcdat.readthedocs.io/en/stable/api.html) page, I think listing all of these options can be confusing for the user.

1. Python classes
    - https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.regrid2.Regrid2Regridder.html
    - https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.xesmf.XESMFRegridder.html
2. General accessor method 
	- https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal.html
3. Individual accessor method by tool
	- https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal_xesmf.html
	- https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal_regrid2.html

All of these methods achieve the same functions, but go about it in a slightly different way. 
This is the callstack with `xesmf`: `horizontal(...tool="xesmf")` -> `horizonal_xesmf()` -> `XESMFRegridder()`.

### Solution
**I propose we just keep "2. General accessor method" listed in our documentation. I foresee most people using that API since it is the most straightforward to use and most flexible (you can specify `tool="regrid2"` or `tool="xesmf"`).**

### PR DESCRIPTION
**Pull request by jasonb5**
## Description

- Closes #501 
- Adds deprecation notice for `horizontal` and `vertical` methods
- Adds `vertical_xgcm` method
- Moves documentation from `*Regridder` classes to `RegridderAccessor` methods.
- Updates `horizontal_xesmf`, `horizontal_regrid2`, and `vertical_xgcm` docstrings.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

If applicable:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass with my changes (locally and CI/CD build)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have noted that this is a breaking change for a major release (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by tomvothecoder** [comment]
Thanks for this PR. Feel free to assign reviewers whenever PRs are ready to get things rolling. 

I'll do an initial review.

**Comment by tomvothecoder** [comment]
I don't think this PR is ready for review so I'll hold off on reviewing

**Comment by jasonb5** [comment]
@chengzhuzhang @lee1043 @pochedls Feel free to invite other reviewers. I'm hoping these changes will improve the visibility of the regridder documentation. Let me know if anything is still unclear and can be improved, thank you!

**Comment by jasonb5** [comment]
Setting this as a draft as it depends on #507. I'll need to make some additional updates to documentation after it's merged.

**Comment by tomvothecoder** [comment]
Hey @jasonb5, let's push this PR back to give more time for discussion since it is not a crucial for v0.6.0. @chengzhuzhang and @lee1043 are in favor of keeping the `.horizontal()` wrapper that encapsulates all of the tools through the `tool` arg. 

I tried to summarize our discussion at the meeting below:

### Why this PR was kickstarted (#501)
  - Too many regridding APIs for the same functionality -- can be confusing for new users
    - https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal.html
    - https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal_xesmf.html
    - https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.xesmf.XESMFRegridder.html
  - For the [`**options`](https://xcdat.readthedocs.io/en/stable/generated/xarray.Dataset.regridder.horizontal.html) arg, users need to go to the individual API documentations for options (hard to navigate) -- combining them under `.horizontal` will make the docstring too long
    - https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.regrid2.Regrid2Regridder.html#xcdat.regridder.regrid2.Regrid2Regridder
    - https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.xesmf.XESMFRegridder.html#xcdat.regridder.xesmf.XESMFRegridder
  - There is minimal overlap in the options between [regrid2](https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.regrid2.Regrid2Regridder.html#xcdat.regridder.regrid2.Regrid2Regridder) and [xesmf](https://xcdat.readthedocs.io/en/stable/generated/xcdat.regridder.xesmf.XESMFRegridder.html#xcdat.regridder.xesmf.XESMFRegridder)
  - The number of lines for the API is more with the wrapper
    - `ds.regridder.horizontal(...tool="xesmf")` vs. `ds.regridder.horizontal_xesmf()`


### Reasons to keep `.horizontal()` wrapper

  - If users are really interested in the regridder options, they will read the docstring and go to the individual API pages
  - It gives more flexibility in usage and testing since the `tool` argument just needs to be swapped
  - `xesmf` is a widely used tool and should be the default option
    - `regrid2` is mainly for CDAT users who need to reproduce the same results using xCDAT

**Comment by tomvothecoder** [comment]
I came across this style of reusable docstrings in xarray. It might be useful if we want to consolidate and reuse docstrings:

https://github.com/pydata/xarray/blob/main/xarray/core/weighted.py#L25-L52
https://github.com/pydata/xarray/blob/1146c5a3cdb15d402e95153c3ea68826b158d953/xarray/core/weighted.py#L546-L569

**Comment by jasonb5** [comment]
Closing as we've decided to stick with generic `horizontal` and `vertical` methods. PR #535 addresses the documentation changes in this PR.

**Pull request closed without merging**
