### PR TITLE
 [PR]: Simplify the contributing guide

### LINKED ISSUE #590: [Doc]: Simplify the contributing guide
### Describe your documentation update

The contributing guide that I wrote awhile back is pretty lengthy and can be unnecessarily technical for new contributors. This might deter people from wanting to contribute to xCDAT.

We should aim to:
- Make getting started simple (e.g., repo and environment setup)
- Make requirements a bit more flexible (e.g., fork vs. write access)
- Make it easy to use `pre-commit` and CI/CD tools

### PR DESCRIPTION
**Pull request by tomvothecoder**
## Description

- Closes #590 
- Now based on and inspired by Xarray [contributing guide](https://docs.xarray.dev/en/stable/contributing.html)

## Todo list

- [x] Add Overview section
- [x] Add Where to start? section
  - [x] Documentation updates
  - [x] Bug reports
  - [x] Enhancement requests
  - [x] All other inquiries 
- [x] Add Version control, Git, and GitHub section
  - [x] Getting started with Git
- [x] Add Creating a development environment section
  - [x] Install pre-commit hooks
- [x]  Add Contributing to codebase section
  - [x] Pull Request (PR)
  - [x] Code Formatting
  - [x] Testing with Continuous Integration
  - [x] Writing Tests 
- [x] Add Developer Tips section
  - [x] Helpful commands
  - [x] xCDAT and Visual Studio Code

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

If applicable:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass with my changes (locally and CI/CD build)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have noted that this is a breaking change for a major release (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by tomvothecoder** [comment]
Hey @xCDAT/core-developers, here is my initial PR draft to simplify the contributing guide. It is based on Xarray's contributing guide, but geared towards xCDAT and made even simpler.

If any of you are available for a quick review, that would be great. You can review the page directly in this Read The Docs preview: https://xcdat.readthedocs.io/en/update-contributing-guide/contributing.html#code-formatting. Thanks!

**Comment by tomvothecoder** [comment]
Hi @chengzhuzhang, just tagging you for review on this PR. It's not urgent, so whenever you have time for it would be great.

**Review by pochedls — COMMENTED** [review]
@tomvothecoder – I did [make some changes](https://github.com/pochedls/xcdat/commit/564aa68040a637913474f4a5ae05a036e8875788) locally (from my forked repo). I basically just deleted mamba stuff ([conda now uses the mamba solver by default](https://docs.conda.io/projects/conda/en/latest/release-notes.html#id23)).

I had some git setup steps (I tried to start from scratch), e.g.,: 

```
git config --global user.name “…”
git config --global user.email “…”
```

But I think that can be beyond the scope of our developer guide. We may need to help some of our users with git stuff.

**Comment by tomvothecoder** [comment]
> @tomvothecoder – I did [make some changes](https://github.com/pochedls/xcdat/commit/564aa68040a637913474f4a5ae05a036e8875788) locally (from my forked repo). I basically just deleted mamba stuff ([conda now uses the mamba solver by default](https://docs.conda.io/projects/conda/en/latest/release-notes.html#id23)).

@pochedls Thanks for the reminder about this update to Conda's default solver. In this [commit](https://github.com/xCDAT/xcdat/pull/593/commits/6b5d6c4c54f7dfae1ce6d15eedebc1e804f4b6e3#diff-71a537d41eec44b10fa3969551f44a15701ad3b600c369e5bb9232c3bf4359f6) I added your suggestions and updated the Installation page to change `mamba` references back to `conda`. 

> 
> I had some git setup steps (I tried to start from scratch), e.g.,:
> 
> ```
> git config --global user.name “…”
> git config --global user.email “…”
> ```
> 
> But I think that can be beyond the scope of our developer guide. We may need to help some of our users with git stuff.

I added a section on setting up the repo by either cloning or forking (this [commit](https://github.com/xCDAT/xcdat/pull/593/commits/2c1c766515a10003e8e18e0071fa14ed297dc32a#diff-76e7ca2f2843ac5f659b45382768c1b64bf8704e8d3c6189c4e3623f5d465bc2)).

My thinking was that adding git content would make the contributing lengthy. From my experience, the basic commands are easy to look up (configs, cloning, fetching, pulling, pushing, and rebasing). As an alternative, we can help individual contributors directly if they have issues with Git.

**Comment by tomvothecoder** [comment]
@pochedls Just bugging you again for your approval

**Review by pochedls — APPROVED** [review]
Looks good. A couple minor comments:

* Consider replacing `repo` with `repository`
* [This section](https://xcdat.readthedocs.io/en/update-contributing-guide/contributing.html#creating-a-development-environment) might have issues. 
  * Doesn't the first code block do (1) and (2)? Should the following be outside the code block?: 
   * This will create the new environment, and not touch any of your existing environments, nor any existing Python installation.

**Comment by tomvothecoder** [comment]
>  - Doesn't the first code block do (1) and (2)? Should the following be outside the code block?:

(1) does not do (2). (1) Creates the dev environment with all of the dependencies required xCDAT, while (2) builds and installs the local version of `xcdat` into the dev environment since we don't include the stable version of xcdat in the dev env (e.g., xcdat=0.7.0`).  (2) allows the user to test/try code changes in the env.

**Comment by pochedls** [comment]
Doesn't `make install # or python -m pip install .` in the code block under *1. Install the build dependencies* actually build/install xcdat?

It seems like the code block under *2. Build and install xcdat* simply ensures that it was built correctly and shows up as a loadable module (i.e., it does not build/install xcdat, which was done under buller 1)?

**Comment by tomvothecoder** [comment]
> Doesn't `make install # or python -m pip install .` in the code block under _1. Install the build dependencies_ actually build/install xcdat?
> 
> It seems like the code block under _2. Build and install xcdat_ simply ensures that it was built correctly and shows up as a loadable module (i.e., it does not build/install xcdat, which was done under buller 1)?
> 
> Note that I am looking at [this rendered page](https://xcdat.readthedocs.io/en/update-contributing-guide/contributing.html#creating-a-development-environment).

Ohhh I see what you're saying. (2) should be labeled "Import the local build of xCDAT". Thanks for catching this.

**Comment by tomvothecoder** [comment]
I addressed the suggestions and will merge this PR now.

**Pull request merged**
