### PR TITLE
Update documentation

### LINKED ISSUE #363: [Doc]: Misc. updates
### Describe your documentation update

- [x] Update https://xcdat.readthedocs.io/en/latest/#stay-up-to-date-with-releases with info on conda-forge releases taking about 30mins-1hr after GH releases
- [x] Fix typos (curvilinear)
- [x] Update project overview text for simplicity and clarity
- [x] Add link to xarray tutorials in getting-started

### PR DESCRIPTION
**Pull request by tomvothecoder**
## Description

- Closes #363 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

If applicable:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass with my changes (locally and CI/CD build)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have noted that this is a breaking change for a major release (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
Hey @tomvothecoder, E3SM output mostly follows CF-convention and we strive to convert non-compliant items when possible.  I think we can rephrase it as:  "Support for CF compliant, non-CF compliant but common metadata"?

**Comment by pochedls** [comment]
> Hey @tomvothecoder, E3SM output mostly follows CF-convention and we strive to convert non-compliant items when possible. I think we can rephrase it as: "Support for CF compliant, non-CF compliant but common metadata"?

This sounds good to me. We might re-phrase to something like: "xcdat supports CF compliant datasets, but will also strive to support datasets with common non-CF compliant metadata."

**Comment by lee1043** [comment]
I like the way @pochedls rephrased!

**Comment by tomvothecoder** [comment]
Thanks for the feedback everyone! I followed Steve's rephrased description.

**Pull request merged**
