### PR TITLE
[Doc]: Add `xsearch` demo notebook for CWSS Presentation

### PR DESCRIPTION
**Pull request by tomvothecoder**
## Description

This PR adds the `xsearch` demo notebook that @pochedls wrote. It demonstrates finding datasets using `xsearch`, then performing analysis on those datasets using `xcdat`.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

If applicable:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass with my changes (locally and CI/CD build)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have noted that this is a breaking change for a major release (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by tomvothecoder** [comment]
Hi @pochedls, I added your `xsearch` notebook into the `/docs/demos` folder. I intend on hosting it on Read the Docs to serve as an example of how `xcdat` can be integrated into analysis workflows with other tools such as `xsearch`. I am adding some markdown cells to your notebook right now. Feel free to check it out early or wait until I am ready for review.

For our CWSS Presentation, I think we should present the [Gentle Introduction Notebook](https://xcdat.readthedocs.io/en/latest/examples/introduction-to-xcdat.html) and then transition to this `xsearch` notebook. I'm going to time how long it takes to present the Gentle Intro Notebook and adjust slides as needed.

**Comment by pochedls** [comment]
@tomvothecoder - Do we want this posted as an xcdat document/demo? It references local data and uses a local tool (xsearch).

**Comment by pochedls** [comment]
> > @tomvothecoder - Do we want this posted as an xcdat document/demo? It references local data and uses a local tool (xsearch).
> 
> That's a good point about the local tool and local data being referenced.
> 
> We can keep it in the `docs/demos` folder to have it version controlled and available for internal reference/demos. We don't need to host it on Read the Docs. Let me know how that sounds.

Sounds good.

**Comment by tomvothecoder** [comment]
A few issues that I need to fix:
 - [ ] Fix grid plots not rendering in notebook
 - [ ] Images inserted in markdown cells using HTML are not being exported in PDF -- must convert to markdown images instead
   - https://github.com/jupyter/nbconvert/issues/552#issuecomment-570377056
   - https://github.com/jupyter/nbconvert/issues/552
 - [ ] Export to PDF (option 3)
    - https://mljar.com/blog/jupyter-notebook-pdf/

**Pull request merged**
